### ISSUE TITLE
Could you tell me where is the file "route_distances"? I can't find it.

### ISSUE THREAD

**Issue by xian-sh** [MolecularAI/PaRoutes#3]
the file "route_distances" is used as follow, path is  "analysis/route_clusters.py"

import route_distances.lstm.defaults as defaults
from route_distances.route_distances import route_distances_calculator
from route_distances.clustering import ClusteringHelper
from route_distances.utils.type_utils import RouteDistancesCalculator

**Comment by SGenheden** [comment]
The `route_distances` is a Python package that should have been installed with the setup instructions.
